name: Auto Merge, Update Version, and Release

on:
  workflow_dispatch:

jobs:
  merge-update-release:   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          release_name: Release ${{ steps.bump_version.outputs.new_version }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false
